from enum import Enum


class PermissionsChangeAddItem(str, Enum):
    CREATE_CATALOG = "CREATE CATALOG"
    CREATE_EXTERNAL_LOCATION = "CREATE EXTERNAL LOCATION"
    CREATE_EXTERNAL_TABLE = "CREATE EXTERNAL TABLE"
    CREATE_EXTERNAL_VOLUME = "CREATE EXTERNAL VOLUME"
    CREATE_FUNCTION = "CREATE FUNCTION"
    CREATE_MANAGED_STORAGE = "CREATE MANAGED STORAGE"
    CREATE_MODEL = "CREATE MODEL"
    CREATE_SCHEMA = "CREATE SCHEMA"
    CREATE_STORAGE_CREDENTIAL = "CREATE STORAGE CREDENTIAL"
    CREATE_TABLE = "CREATE TABLE"
    CREATE_VOLUME = "CREATE VOLUME"
    EXECUTE = "EXECUTE"
    MODIFY = "MODIFY"
    READ_FILES = "READ FILES"
    READ_VOLUME = "READ VOLUME"
    SELECT = "SELECT"
    USE_CATALOG = "USE CATALOG"
    USE_SCHEMA = "USE SCHEMA"
    WRITE_FILES = "WRITE FILES"

    def __str__(self) -> str:
        return str(self.value)
